spring:
  application:
    name: service-producer

---
spring:
  profiles: p1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8763


---
spring:
  profiles: p2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8764








